sudo: required
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 10.9.0
before_script:
  - yarn global add gulp-cli
  - yarn
script:
  - npm run lint
  - yarn test
  - yarn run flow
