sudo: required
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 8.9.3
before_script:
  - yarn global add gulp-cli
  - yarn
script:
  - npm run lint
  - yarn jest
  - yarn run flow
  - yarn storybook:snapshot
