sudo: required
dist: xenial
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - node -v
  - yarn
script:
  - yarn build-storybook
  - bash <(curl -s https://peek.run/ci)
  - yarn lint
  - yarn prettier:ci
  - yarn test
  - yarn flow
